# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/generic_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gen_window(object):
    def setupUi(self, gen_window):
        gen_window.setObjectName("gen_window")
        gen_window.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gen_window.sizePolicy().hasHeightForWidth())
        gen_window.setSizePolicy(sizePolicy)
        gen_window.setMinimumSize(QtCore.QSize(800, 480))
        gen_window.setMaximumSize(QtCore.QSize(1920, 1080))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 151, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 151, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 151, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        gen_window.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        gen_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/h-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gen_window.setWindowIcon(icon)
        self.gen_widget = QtWidgets.QWidget(gen_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gen_widget.sizePolicy().hasHeightForWidth())
        self.gen_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gen_widget.setFont(font)
        self.gen_widget.setObjectName("gen_widget")
        self.menu = QtWidgets.QTabWidget(self.gen_widget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 800, 430))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 109, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 145, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 109, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 145, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 109, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 236, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 109, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 145, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 109, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 109, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 218, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.menu.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.pwr_status = QtWidgets.QWidget()
        self.pwr_status.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pwr_status.setFont(font)
        self.pwr_status.setObjectName("pwr_status")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.pwr_status)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 158, 791, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.pwr_status_deck = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.pwr_status_deck.setContentsMargins(0, 0, 0, 0)
        self.pwr_status_deck.setObjectName("pwr_status_deck")
        self.p1_status = QtWidgets.QHBoxLayout()
        self.p1_status.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p1_status.setContentsMargins(0, -1, -1, -1)
        self.p1_status.setObjectName("p1_status")
        self.p1_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_label.sizePolicy().hasHeightForWidth())
        self.p1_label.setSizePolicy(sizePolicy)
        self.p1_label.setObjectName("p1_label")
        self.p1_status.addWidget(self.p1_label)
        self.p1_vread = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_vread.sizePolicy().hasHeightForWidth())
        self.p1_vread.setSizePolicy(sizePolicy)
        self.p1_vread.setSmallDecimalPoint(True)
        self.p1_vread.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_vread.setProperty("value", -1.0)
        self.p1_vread.setProperty("intValue", -1)
        self.p1_vread.setObjectName("p1_vread")
        self.p1_status.addWidget(self.p1_vread)
        self.u1_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u1_label.sizePolicy().hasHeightForWidth())
        self.u1_label.setSizePolicy(sizePolicy)
        self.u1_label.setObjectName("u1_label")
        self.p1_status.addWidget(self.u1_label)
        self.p1_cread = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_cread.sizePolicy().hasHeightForWidth())
        self.p1_cread.setSizePolicy(sizePolicy)
        self.p1_cread.setSmallDecimalPoint(True)
        self.p1_cread.setMode(QtWidgets.QLCDNumber.Dec)
        self.p1_cread.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p1_cread.setProperty("value", -1.0)
        self.p1_cread.setProperty("intValue", -1)
        self.p1_cread.setObjectName("p1_cread")
        self.p1_status.addWidget(self.p1_cread)
        self.u2_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u2_label.sizePolicy().hasHeightForWidth())
        self.u2_label.setSizePolicy(sizePolicy)
        self.u2_label.setObjectName("u2_label")
        self.p1_status.addWidget(self.u2_label)
        self.pwr_status_deck.addLayout(self.p1_status)
        self.p2_status = QtWidgets.QHBoxLayout()
        self.p2_status.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p2_status.setContentsMargins(0, -1, -1, -1)
        self.p2_status.setObjectName("p2_status")
        self.p2_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2_label.sizePolicy().hasHeightForWidth())
        self.p2_label.setSizePolicy(sizePolicy)
        self.p2_label.setObjectName("p2_label")
        self.p2_status.addWidget(self.p2_label)
        self.p2_vread = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2_vread.sizePolicy().hasHeightForWidth())
        self.p2_vread.setSizePolicy(sizePolicy)
        self.p2_vread.setSmallDecimalPoint(True)
        self.p2_vread.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p2_vread.setProperty("value", -1.0)
        self.p2_vread.setProperty("intValue", -1)
        self.p2_vread.setObjectName("p2_vread")
        self.p2_status.addWidget(self.p2_vread)
        self.u3_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u3_label.sizePolicy().hasHeightForWidth())
        self.u3_label.setSizePolicy(sizePolicy)
        self.u3_label.setObjectName("u3_label")
        self.p2_status.addWidget(self.u3_label)
        self.p2_cread = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2_cread.sizePolicy().hasHeightForWidth())
        self.p2_cread.setSizePolicy(sizePolicy)
        self.p2_cread.setSmallDecimalPoint(True)
        self.p2_cread.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p2_cread.setProperty("value", -1.0)
        self.p2_cread.setProperty("intValue", -1)
        self.p2_cread.setObjectName("p2_cread")
        self.p2_status.addWidget(self.p2_cread)
        self.u4_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u4_label.sizePolicy().hasHeightForWidth())
        self.u4_label.setSizePolicy(sizePolicy)
        self.u4_label.setObjectName("u4_label")
        self.p2_status.addWidget(self.u4_label)
        self.pwr_status_deck.addLayout(self.p2_status)
        self.p3_status = QtWidgets.QHBoxLayout()
        self.p3_status.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p3_status.setContentsMargins(0, -1, -1, -1)
        self.p3_status.setObjectName("p3_status")
        self.p3_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_label.sizePolicy().hasHeightForWidth())
        self.p3_label.setSizePolicy(sizePolicy)
        self.p3_label.setObjectName("p3_label")
        self.p3_status.addWidget(self.p3_label)
        self.p3_vread = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_vread.sizePolicy().hasHeightForWidth())
        self.p3_vread.setSizePolicy(sizePolicy)
        self.p3_vread.setSmallDecimalPoint(True)
        self.p3_vread.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p3_vread.setProperty("value", -1.0)
        self.p3_vread.setProperty("intValue", -1)
        self.p3_vread.setObjectName("p3_vread")
        self.p3_status.addWidget(self.p3_vread)
        self.u5_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u5_label.sizePolicy().hasHeightForWidth())
        self.u5_label.setSizePolicy(sizePolicy)
        self.u5_label.setObjectName("u5_label")
        self.p3_status.addWidget(self.u5_label)
        self.p3_cread = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_cread.sizePolicy().hasHeightForWidth())
        self.p3_cread.setSizePolicy(sizePolicy)
        self.p3_cread.setSmallDecimalPoint(True)
        self.p3_cread.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.p3_cread.setProperty("value", -1.0)
        self.p3_cread.setProperty("intValue", -1)
        self.p3_cread.setObjectName("p3_cread")
        self.p3_status.addWidget(self.p3_cread)
        self.u6_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.u6_label.sizePolicy().hasHeightForWidth())
        self.u6_label.setSizePolicy(sizePolicy)
        self.u6_label.setObjectName("u6_label")
        self.p3_status.addWidget(self.u6_label)
        self.pwr_status_deck.addLayout(self.p3_status)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pwr_status)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.pwr_connections_deck = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.pwr_connections_deck.setContentsMargins(0, 0, 0, 0)
        self.pwr_connections_deck.setObjectName("pwr_connections_deck")
        self.pc_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pc_1.setFont(font)
        self.pc_1.setObjectName("pc_1")
        self.pwr_connections_deck.addWidget(self.pc_1)
        self.pstat_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pstat_1.setScaledContents(True)
        self.pstat_1.setIndent(20)
        self.pstat_1.setObjectName("pstat_1")
        self.pwr_connections_deck.addWidget(self.pstat_1)
        self.pc_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pc_2.setFont(font)
        self.pc_2.setObjectName("pc_2")
        self.pwr_connections_deck.addWidget(self.pc_2)
        self.pstat_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pstat_2.setScaledContents(True)
        self.pstat_2.setIndent(20)
        self.pstat_2.setObjectName("pstat_2")
        self.pwr_connections_deck.addWidget(self.pstat_2)
        self.pc_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pc_3.setFont(font)
        self.pc_3.setObjectName("pc_3")
        self.pwr_connections_deck.addWidget(self.pc_3)
        self.pstat_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.pstat_3.setScaledContents(True)
        self.pstat_3.setIndent(20)
        self.pstat_3.setObjectName("pstat_3")
        self.pwr_connections_deck.addWidget(self.pstat_3)
        self.menu.addTab(self.pwr_status, "")
        self.pwr_ctrl = QtWidgets.QWidget()
        self.pwr_ctrl.setEnabled(True)
        self.pwr_ctrl.setAutoFillBackground(False)
        self.pwr_ctrl.setObjectName("pwr_ctrl")
        self.menu.addTab(self.pwr_ctrl, "")
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.menu.addTab(self.graph, "")
        gen_window.setCentralWidget(self.gen_widget)
        self.m_bar = QtWidgets.QMenuBar(gen_window)
        self.m_bar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.m_bar.setObjectName("m_bar")
        self.mt_file = QtWidgets.QMenu(self.m_bar)
        self.mt_file.setObjectName("mt_file")
        self.mt_edit = QtWidgets.QMenu(self.m_bar)
        self.mt_edit.setObjectName("mt_edit")
        gen_window.setMenuBar(self.m_bar)
        self.status = QtWidgets.QStatusBar(gen_window)
        self.status.setObjectName("status")
        gen_window.setStatusBar(self.status)
        self.m_open = QtWidgets.QAction(gen_window)
        self.m_open.setObjectName("m_open")
        self.m_save = QtWidgets.QAction(gen_window)
        self.m_save.setObjectName("m_save")
        self.m_new = QtWidgets.QAction(gen_window)
        self.m_new.setObjectName("m_new")
        self.m_copy = QtWidgets.QAction(gen_window)
        self.m_copy.setObjectName("m_copy")
        self.m_paste = QtWidgets.QAction(gen_window)
        self.m_paste.setObjectName("m_paste")
        self.mt_file.addAction(self.m_new)
        self.mt_file.addAction(self.m_open)
        self.mt_file.addAction(self.m_save)
        self.mt_edit.addAction(self.m_copy)
        self.mt_edit.addAction(self.m_paste)
        self.m_bar.addAction(self.mt_file.menuAction())
        self.m_bar.addAction(self.mt_edit.menuAction())

        self.retranslateUi(gen_window)
        self.menu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(gen_window)

    def retranslateUi(self, gen_window):
        _translate = QtCore.QCoreApplication.translate
        gen_window.setWindowTitle(_translate("gen_window", "MainWindow"))
        self.p1_label.setText(_translate("gen_window", "PWR 1"))
        self.u1_label.setText(_translate("gen_window", "Volts"))
        self.u2_label.setText(_translate("gen_window", "Amps"))
        self.p2_label.setText(_translate("gen_window", "PWR 2"))
        self.u3_label.setText(_translate("gen_window", "Volts"))
        self.u4_label.setText(_translate("gen_window", "Amps"))
        self.p3_label.setText(_translate("gen_window", "PWR 3"))
        self.u5_label.setText(_translate("gen_window", "Volts"))
        self.u6_label.setText(_translate("gen_window", "Amps"))
        self.pc_1.setText(_translate("gen_window", "PWR 1:"))
        self.pstat_1.setText(_translate("gen_window", "N/A"))
        self.pc_2.setText(_translate("gen_window", "PWR 2:"))
        self.pstat_2.setText(_translate("gen_window", "N/A"))
        self.pc_3.setText(_translate("gen_window", "PWR 3:"))
        self.pstat_3.setText(_translate("gen_window", "N/A"))
        self.menu.setTabText(self.menu.indexOf(self.pwr_status), _translate("gen_window", "Status"))
        self.menu.setTabText(self.menu.indexOf(self.pwr_ctrl), _translate("gen_window", "Control"))
        self.menu.setTabText(self.menu.indexOf(self.graph), _translate("gen_window", "Graph"))
        self.mt_file.setTitle(_translate("gen_window", "File"))
        self.mt_edit.setTitle(_translate("gen_window", "Edit"))
        self.m_open.setText(_translate("gen_window", "Open"))
        self.m_open.setStatusTip(_translate("gen_window", "Open a preexisting file"))
        self.m_open.setShortcut(_translate("gen_window", "Ctrl+O"))
        self.m_save.setText(_translate("gen_window", "Save"))
        self.m_save.setStatusTip(_translate("gen_window", "Save to file"))
        self.m_save.setShortcut(_translate("gen_window", "Ctrl+S"))
        self.m_new.setText(_translate("gen_window", "New"))
        self.m_new.setStatusTip(_translate("gen_window", "Create a new file"))
        self.m_new.setShortcut(_translate("gen_window", "Ctrl+N"))
        self.m_copy.setText(_translate("gen_window", "Copy"))
        self.m_copy.setStatusTip(_translate("gen_window", "Copy graph data"))
        self.m_copy.setShortcut(_translate("gen_window", "Ctrl+C"))
        self.m_paste.setText(_translate("gen_window", "Paste"))
        self.m_paste.setStatusTip(_translate("gen_window", "Paste graph data"))
        self.m_paste.setShortcut(_translate("gen_window", "Ctrl+V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gen_window = QtWidgets.QMainWindow()
    ui = Ui_gen_window()
    ui.setupUi(gen_window)
    gen_window.show()
    sys.exit(app.exec_())
