# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/generic_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gen_window(object):
    def setupUi(self, gen_window):
        gen_window.setObjectName("gen_window")
        gen_window.resize(640, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gen_window.sizePolicy().hasHeightForWidth())
        gen_window.setSizePolicy(sizePolicy)
        gen_window.setMinimumSize(QtCore.QSize(640, 475))
        self.gen_widget = QtWidgets.QWidget(gen_window)
        self.gen_widget.setObjectName("gen_widget")
        self.c_pannel = QtWidgets.QGroupBox(self.gen_widget)
        self.c_pannel.setGeometry(QtCore.QRect(0, 0, 161, 241))
        font = QtGui.QFont()
        font.setFamily("Hack")
        font.setPointSize(14)
        self.c_pannel.setFont(font)
        self.c_pannel.setObjectName("c_pannel")
        self.power_supply = QtWidgets.QComboBox(self.c_pannel)
        self.power_supply.setGeometry(QtCore.QRect(10, 30, 141, 71))
        self.power_supply.setObjectName("power_supply")
        self.power_supply.addItem("")
        self.power_supply.addItem("")
        self.power_supply.addItem("")
        self.control_mode = QtWidgets.QComboBox(self.c_pannel)
        self.control_mode.setGeometry(QtCore.QRect(10, 110, 141, 71))
        self.control_mode.setObjectName("control_mode")
        self.control_mode.addItem("")
        self.control_mode.addItem("")
        self.submit = QtWidgets.QPushButton(self.c_pannel)
        self.submit.setGeometry(QtCore.QRect(10, 190, 141, 41))
        self.submit.setObjectName("submit")
        self.img_sel = QtWidgets.QFrame(self.gen_widget)
        self.img_sel.setGeometry(QtCore.QRect(0, 240, 631, 191))
        self.img_sel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.img_sel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_sel.setObjectName("img_sel")
        self.img = QtWidgets.QLabel(self.img_sel)
        self.img.setGeometry(QtCore.QRect(20, 10, 601, 91))
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap("../imgs/banner.png"))
        self.img.setScaledContents(True)
        self.img.setWordWrap(False)
        self.img.setObjectName("img")
        self.b1_img = QtWidgets.QPushButton(self.img_sel)
        self.b1_img.setGeometry(QtCore.QRect(10, 120, 291, 61))
        self.b1_img.setObjectName("b1_img")
        self.b2_img = QtWidgets.QPushButton(self.img_sel)
        self.b2_img.setGeometry(QtCore.QRect(330, 120, 291, 61))
        self.b2_img.setObjectName("b2_img")
        self.status_pannel = QtWidgets.QGroupBox(self.gen_widget)
        self.status_pannel.setGeometry(QtCore.QRect(170, 10, 451, 221))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.status_pannel.setFont(font)
        self.status_pannel.setObjectName("status_pannel")
        self.lab_pwr1 = QtWidgets.QLabel(self.status_pannel)
        self.lab_pwr1.setGeometry(QtCore.QRect(10, 40, 78, 28))
        self.lab_pwr1.setObjectName("lab_pwr1")
        self.v_pwr1 = QtWidgets.QLabel(self.status_pannel)
        self.v_pwr1.setGeometry(QtCore.QRect(100, 40, 100, 28))
        self.v_pwr1.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.v_pwr1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.v_pwr1.setFont(font)
        self.v_pwr1.setAutoFillBackground(True)
        self.v_pwr1.setStyleSheet("")
        self.v_pwr1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v_pwr1.setTextFormat(QtCore.Qt.PlainText)
        self.v_pwr1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.v_pwr1.setIndent(5)
        self.v_pwr1.setObjectName("v_pwr1")
        self.v_pwr2 = QtWidgets.QLabel(self.status_pannel)
        self.v_pwr2.setGeometry(QtCore.QRect(100, 80, 100, 28))
        self.v_pwr2.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.v_pwr2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.v_pwr2.setFont(font)
        self.v_pwr2.setAutoFillBackground(True)
        self.v_pwr2.setStyleSheet("")
        self.v_pwr2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v_pwr2.setTextFormat(QtCore.Qt.PlainText)
        self.v_pwr2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.v_pwr2.setIndent(5)
        self.v_pwr2.setObjectName("v_pwr2")
        self.lab_pwr2 = QtWidgets.QLabel(self.status_pannel)
        self.lab_pwr2.setGeometry(QtCore.QRect(10, 80, 78, 28))
        self.lab_pwr2.setObjectName("lab_pwr2")
        self.v_pwr3 = QtWidgets.QLabel(self.status_pannel)
        self.v_pwr3.setGeometry(QtCore.QRect(100, 120, 100, 28))
        self.v_pwr3.setMinimumSize(QtCore.QSize(100, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 34, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.v_pwr3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.v_pwr3.setFont(font)
        self.v_pwr3.setAutoFillBackground(True)
        self.v_pwr3.setStyleSheet("")
        self.v_pwr3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v_pwr3.setTextFormat(QtCore.Qt.PlainText)
        self.v_pwr3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.v_pwr3.setIndent(5)
        self.v_pwr3.setObjectName("v_pwr3")
        self.lab_pwr3 = QtWidgets.QLabel(self.status_pannel)
        self.lab_pwr3.setGeometry(QtCore.QRect(10, 120, 78, 28))
        self.lab_pwr3.setObjectName("lab_pwr3")
        gen_window.setCentralWidget(self.gen_widget)
        self.m_bar = QtWidgets.QMenuBar(gen_window)
        self.m_bar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.m_bar.setObjectName("m_bar")
        self.mt_file = QtWidgets.QMenu(self.m_bar)
        self.mt_file.setObjectName("mt_file")
        self.mt_edit = QtWidgets.QMenu(self.m_bar)
        self.mt_edit.setObjectName("mt_edit")
        gen_window.setMenuBar(self.m_bar)
        self.status = QtWidgets.QStatusBar(gen_window)
        self.status.setObjectName("status")
        gen_window.setStatusBar(self.status)
        self.m_open = QtWidgets.QAction(gen_window)
        self.m_open.setObjectName("m_open")
        self.m_save = QtWidgets.QAction(gen_window)
        self.m_save.setObjectName("m_save")
        self.m_new = QtWidgets.QAction(gen_window)
        self.m_new.setObjectName("m_new")
        self.m_copy = QtWidgets.QAction(gen_window)
        self.m_copy.setObjectName("m_copy")
        self.m_paste = QtWidgets.QAction(gen_window)
        self.m_paste.setObjectName("m_paste")
        self.mt_file.addAction(self.m_new)
        self.mt_file.addAction(self.m_open)
        self.mt_file.addAction(self.m_save)
        self.mt_edit.addAction(self.m_copy)
        self.mt_edit.addAction(self.m_paste)
        self.m_bar.addAction(self.mt_file.menuAction())
        self.m_bar.addAction(self.mt_edit.menuAction())

        self.retranslateUi(gen_window)
        QtCore.QMetaObject.connectSlotsByName(gen_window)

    def retranslateUi(self, gen_window):
        _translate = QtCore.QCoreApplication.translate
        gen_window.setWindowTitle(_translate("gen_window", "MainWindow"))
        self.c_pannel.setTitle(_translate("gen_window", "Control Pannel"))
        self.power_supply.setItemText(0, _translate("gen_window", "Pwr 1"))
        self.power_supply.setItemText(1, _translate("gen_window", "Pwr 2"))
        self.power_supply.setItemText(2, _translate("gen_window", "Pwr 3"))
        self.control_mode.setItemText(0, _translate("gen_window", "Voltage (V)"))
        self.control_mode.setItemText(1, _translate("gen_window", "Current (mA)"))
        self.submit.setText(_translate("gen_window", "Submit"))
        self.b1_img.setText(_translate("gen_window", "Image 1"))
        self.b2_img.setText(_translate("gen_window", "Image 2"))
        self.status_pannel.setTitle(_translate("gen_window", "Status Pannel"))
        self.lab_pwr1.setText(_translate("gen_window", "Pwr 1:"))
        self.v_pwr1.setText(_translate("gen_window", "N/A"))
        self.v_pwr2.setText(_translate("gen_window", "N/A"))
        self.lab_pwr2.setText(_translate("gen_window", "Pwr 2:"))
        self.v_pwr3.setText(_translate("gen_window", "N/A"))
        self.lab_pwr3.setText(_translate("gen_window", "Pwr 3:"))
        self.mt_file.setTitle(_translate("gen_window", "File"))
        self.mt_edit.setTitle(_translate("gen_window", "Edit"))
        self.m_open.setText(_translate("gen_window", "Open"))
        self.m_open.setStatusTip(_translate("gen_window", "Open a preexisting file"))
        self.m_open.setShortcut(_translate("gen_window", "Ctrl+O"))
        self.m_save.setText(_translate("gen_window", "Save"))
        self.m_save.setStatusTip(_translate("gen_window", "Save to file"))
        self.m_save.setShortcut(_translate("gen_window", "Ctrl+S"))
        self.m_new.setText(_translate("gen_window", "New"))
        self.m_new.setStatusTip(_translate("gen_window", "Create a new file"))
        self.m_new.setShortcut(_translate("gen_window", "Ctrl+N"))
        self.m_copy.setText(_translate("gen_window", "Copy"))
        self.m_copy.setStatusTip(_translate("gen_window", "Copy graph data"))
        self.m_copy.setShortcut(_translate("gen_window", "Ctrl+C"))
        self.m_paste.setText(_translate("gen_window", "Paste"))
        self.m_paste.setStatusTip(_translate("gen_window", "Paste graph data"))
        self.m_paste.setShortcut(_translate("gen_window", "Ctrl+V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gen_window = QtWidgets.QMainWindow()
    ui = Ui_gen_window()
    ui.setupUi(gen_window)
    gen_window.show()
    sys.exit(app.exec_())
